
# Set the mode of prediction
chatbot_mode: keyword 

# Configuaryion for the keyword extractor
language: 'en'
max_ngram_size: 3
deduplication_threshold: 0.9
deduplication_algo: 'seqm'
windowSize: 1
numOfKeywords: 10

# Configurations to fetch context
user_agent: 'ChatBot/1.0 (thushara.nair02@gmail.com)'
sentence_transformer: 'paraphrase-MiniLM-L6-v2'

# Model for prediction 
model_name: 'deepset/roberta-base-squad2'